version: '3.8'

services:
  app-data:
    image: postgres:17.2
    container_name: app-data
    environment:
      POSTGRES_USER: ${USER_PGSQL}
      POSTGRES_PASSWORD: ${PASS_PGSQL}
      POSTGRES_DB: ${NAME_PGSQL}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_PGSQL} -d ${NAME_PGSQL}"]
      interval: 5s
      timeout: 5s
      retries: 5

  flask-api:
    build: .  # ← Esta linha é ESSENCIAL
    container_name: flask-api
    ports:
      - "5000:5000"
    depends_on:
      app-data:
        condition: service_healthy
    environment:
      - HOST_PGSQL=app-data
      - NAME_PGSQL=${NAME_PGSQL}
      - USER_PGSQL=${USER_PGSQL}
      - PASS_PGSQL=${PASS_PGSQL}
    volumes:
      - .:/app

volumes:
  postgres_data: